[versions]
androidGradlePlugin = "8.0.2"
kotlin = "1.9.22"

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }